name: portfolio
description: An absolute bare-bones web app.
version: 2021.1.0
homepage: https://tenhobi.dev
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  intl: ^0.20.2

dev_dependencies:
  build_runner: ^2.4.15
  build_web_compilers: ^4.1.0
